import { useEffect, useMemo, useState } from "react";

const API_URL = import.meta.env.VITE_API_URL || (import.meta.env.DEV ? "http://localhost:5000/api" : "/api");
const money = new Intl.NumberFormat("th-TH", { style: "currency", currency: "THB", maximumFractionDigits: 0 });

export default function CartDrawer({ onClose, onRequireLogin }) {
  const token = localStorage.getItem("token");
  const [cart, setCart] = useState(null);
  const [message, setMessage] = useState("");
  const request = async (path, options = {}) => { const response = await fetch(`${API_URL}/cart${path}`, { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, ...options.headers } }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to update cart"); return data; };
  useEffect(() => { if (token) request("").then(setCart).catch((error) => setMessage(error.message)); }, []);
  const total = useMemo(() => (cart?.items || []).reduce((sum, item) => sum + (item.product?.price || 0) * (1 - (item.product?.discountPercent || 0) / 100) * item.quantity, 0), [cart]);
  const change = async (id, quantity) => { try { setCart(await request(`/${id}`, { method: "PATCH", body: JSON.stringify({ quantity }) })); } catch (error) { setMessage(error.message); } };
  const remove = async (id) => { try { setCart(await request(`/${id}`, { method: "DELETE" })); } catch (error) { setMessage(error.message); } };
  return <div className="fixed inset-0 z-50 bg-slate-950/50" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside className="ml-auto flex h-full w-full max-w-md flex-col bg-white p-6 shadow-2xl" role="dialog" aria-modal="true"><div className="flex items-center justify-between"><h2 className="text-2xl font-black text-slate-900">Shopping cart</h2><button onClick={onClose} className="text-2xl text-slate-500">×</button></div>{!token ? <div className="grid flex-1 place-items-center text-center"><div><p className="text-slate-600">Please log in before viewing your cart.</p><button onClick={onRequireLogin} className="mt-4 rounded-lg bg-blue-600 px-4 py-2 font-bold text-white">Log in</button></div></div> : <><div className="mt-5 flex-1 space-y-4 overflow-y-auto">{message && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{message}</p>}{!cart ? <p className="text-slate-500">Loading cart...</p> : cart.items.length === 0 ? <p className="text-slate-500">Your cart is empty.</p> : cart.items.map((item) => <article key={item._id} className="border-b border-slate-200 pb-4"><p className="font-bold text-slate-900">{item.product?.name || "Unavailable product"}</p><p className="text-sm text-slate-500">US {item.size}</p><p className="font-semibold">{money.format((item.product?.price || 0) * (1 - (item.product?.discountPercent || 0) / 100))}</p><div className="mt-2 flex items-center gap-2"><button onClick={() => item.quantity > 1 && change(item._id, item.quantity - 1)} className="rounded border px-2">−</button><span>{item.quantity}</span><button onClick={() => change(item._id, item.quantity + 1)} className="rounded border px-2">+</button><button onClick={() => remove(item._id)} className="ml-auto text-sm font-semibold text-red-600">Remove</button></div></article>)}</div><div className="border-t pt-4"><div className="flex justify-between text-lg font-black"><span>Total</span><span>{money.format(total)}</span></div><button disabled={!cart?.items.length} className="mt-4 w-full rounded-lg bg-slate-900 py-3 font-bold text-white disabled:bg-slate-300">Checkout (coming soon)</button></div></>}</aside></div>;
}
