import { useEffect, useState } from "react";

const API_URL = import.meta.env.VITE_API_URL || (import.meta.env.DEV ? "http://localhost:5000/api" : "/api");
const empty = { name: "", brand: "", sku: "", category: "casual", price: "", color: "", imageUrl: "", sizes: "" };

export default function ProductManager() {
  const [items, setItems] = useState([]); const [form, setForm] = useState(empty); const [imageFile, setImageFile] = useState(null); const [id, setId] = useState(null); const [note, setNote] = useState("");
  const call = async (path, options = {}) => { const r = await fetch(`${API_URL}${path}`, { ...options, headers: { Authorization: `Bearer ${localStorage.getItem("token")}`, ...options.headers } }); if (r.status === 204) return; const data = await r.json(); if (!r.ok) throw new Error(data.message || "Request failed"); return data; };
  const load = async () => { try { setItems(await call("/products?status=available")); } catch (e) { setNote(e.message); } };
  useEffect(() => { load(); }, []);
  const uploadImage = async () => { if (!imageFile) return form.imageUrl; const data = new FormData(); data.append("image", imageFile); const result = await call("/uploads/products", { method: "POST", body: data }); return result.imageUrl; };
  const submit = async (e) => { e.preventDefault(); try { const imageUrl = await uploadImage(); const { imageUrl: ignoredImageUrl, ...details } = form; const payload = { ...details, price: Number(form.price), images: imageUrl ? [imageUrl] : [], sizes: form.sizes.split(",").filter(Boolean).map((x) => { const [size, stock] = x.trim().split(":"); return { size: Number(size), stock: Number(stock || 0) }; }) }; await call(id ? `/products/${id}` : "/products", { method: id ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); setNote(id ? "Product updated" : "Product added"); setForm(empty); setImageFile(null); setId(null); load(); } catch (err) { setNote(err.message); } };
  const edit = (product) => { setId(product._id); setImageFile(null); setForm({ name: product.name, brand: product.brand, sku: product.sku, category: product.category, price: product.price, color: product.color || "", imageUrl: product.images?.[0] || "", sizes: product.sizes?.map((s) => `${s.size}:${s.stock}`).join(", ") || "" }); };
  const remove = async (productId) => { if (!window.confirm("Delete this product?")) return; try { await call(`/products/${productId}`, { method: "DELETE" }); setNote("Product deleted"); load(); } catch (e) { setNote(e.message); } };
  const set = (name) => (e) => setForm({ ...form, [name]: e.target.value }); const style = "rounded border border-slate-300 px-3 py-2 text-sm";
  return <section className="mt-6 border-t border-slate-200 pt-6"><h2 className="text-lg font-bold">Shoe inventory</h2><p className="text-sm text-slate-500">Add, edit, and delete products.</p>{note && <p className="mt-2 text-sm text-blue-700">{note}</p>}<form onSubmit={submit} className="mt-4 grid gap-2"><div className="grid grid-cols-2 gap-2"><input className={style} placeholder="Shoe name" value={form.name} onChange={set("name")} required/><input className={style} placeholder="Brand" value={form.brand} onChange={set("brand")} required/></div><div className="grid grid-cols-2 gap-2"><input className={style} placeholder="SKU" value={form.sku} onChange={set("sku")} required/><select className={style} value={form.category} onChange={set("category")}>{["running", "casual", "basketball", "football", "sandals", "other"].map((x) => <option key={x}>{x}</option>)}</select></div><div className="grid grid-cols-2 gap-2"><input className={style} type="number" min="0" placeholder="Price (THB)" value={form.price} onChange={set("price")} required/><input className={style} placeholder="Color" value={form.color} onChange={set("color")}/></div><input className={style} type="url" placeholder="Image URL (https://...)" value={form.imageUrl} onChange={set("imageUrl")}/><input className={style} placeholder="Sizes: 40:5, 41:2" value={form.sizes} onChange={set("sizes")}/><button className="rounded bg-blue-600 px-3 py-2 text-sm font-semibold text-white">{id ? "Update product" : "Add product"}</button></form><div className="mt-5 space-y-2">{items.map((product) => <article key={product._id} className="flex items-center justify-between rounded-lg bg-slate-50 p-3 text-sm"><div><p className="font-semibold">{product.name} <span className="font-normal text-slate-500">({product.sku})</span></p><p className="text-slate-500">฿{Number(product.price).toLocaleString()} · {product.brand}</p></div><div className="flex gap-2"><button onClick={() => edit(product)} className="text-blue-700">Edit</button><button onClick={() => remove(product._id)} className="text-red-600">Delete</button></div></article>)}</div></section>;
}
