import { useEffect, useState } from "react";

const API_URL = import.meta.env.VITE_API_URL || (import.meta.env.DEV ? "http://localhost:5000/api" : "/api");
const blank = { name: "", brand: "", sku: "", category: "casual", price: "", color: "", sizes: "", imageUrl: "" };

export default function ProductManagerWithUpload() {
  const [products, setProducts] = useState([]); const [form, setForm] = useState(blank); const [imageFile, setImageFile] = useState(null); const [id, setId] = useState(null); const [message, setMessage] = useState("");
  const request = async (path, options = {}) => { const response = await fetch(`${API_URL}${path}`, { ...options, headers: { Authorization: `Bearer ${localStorage.getItem("token")}`, ...options.headers } }); if (response.status === 204) return null; const data = await response.json(); if (!response.ok) throw new Error(data.message || "Request failed"); return data; };
  const load = async () => { try { setProducts(await request("/products?status=available")); } catch (error) { setMessage(error.message); } };
  useEffect(() => { load(); }, []);
  const set = (key) => (event) => setForm({ ...form, [key]: event.target.value });
  const uploadImage = async () => { if (!imageFile) return form.imageUrl; const data = new FormData(); data.append("image", imageFile); const result = await request("/uploads/products", { method: "POST", body: data }); return result.imageUrl; };
  const submit = async (event) => { event.preventDefault(); try { const imageUrl = await uploadImage(); const sizes = form.sizes.split(",").filter(Boolean).map((value) => { const [size, stock] = value.trim().split(":"); return { size: Number(size), stock: Number(stock || 0) }; }); const payload = { ...form, price: Number(form.price), sizes, images: imageUrl ? [imageUrl] : [] }; delete payload.imageUrl; await request(id ? `/products/${id}` : "/products", { method: id ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); setMessage(id ? "Product updated" : "Product added"); setForm(blank); setImageFile(null); setId(null); load(); } catch (error) { setMessage(error.message); } };
  const edit = (product) => { setId(product._id); setImageFile(null); setForm({ name: product.name, brand: product.brand, sku: product.sku, category: product.category, price: product.price, color: product.color || "", sizes: product.sizes?.map((size) => `${size.size}:${size.stock}`).join(", ") || "", imageUrl: product.images?.[0] || "" }); };
  const remove = async (productId) => { if (!window.confirm("Delete this product?")) return; try { await request(`/products/${productId}`, { method: "DELETE" }); setMessage("Product deleted"); load(); } catch (error) { setMessage(error.message); } };
  const field = "rounded border border-slate-300 px-3 py-2 text-sm";
  return <section className="mt-6 border-t border-slate-200 pt-6"><h2 className="text-lg font-bold">Shoe inventory</h2><p className="text-sm text-slate-500">Upload a product image from your device.</p>{message && <p className="mt-2 text-sm text-blue-700">{message}</p>}<form onSubmit={submit} className="mt-4 grid gap-2"><div className="grid grid-cols-2 gap-2"><input className={field} placeholder="Shoe name" value={form.name} onChange={set("name")} required/><input className={field} placeholder="Brand" value={form.brand} onChange={set("brand")} required/></div><div className="grid grid-cols-2 gap-2"><input className={field} placeholder="SKU" value={form.sku} onChange={set("sku")} required/><select className={field} value={form.category} onChange={set("category")}>{["running", "casual", "basketball", "football", "sandals", "other"].map((item) => <option key={item}>{item}</option>)}</select></div><div className="grid grid-cols-2 gap-2"><input className={field} type="number" min="0" placeholder="Price (THB)" value={form.price} onChange={set("price")} required/><input className={field} placeholder="Color" value={form.color} onChange={set("color")}/></div><input className={field} type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => setImageFile(event.target.files?.[0] || null)}/><input className={field} placeholder="Sizes: 40:5, 41:2" value={form.sizes} onChange={set("sizes")}/><button className="rounded bg-blue-600 px-3 py-2 text-sm font-semibold text-white">{id ? "Update product" : "Add product"}</button></form><div className="mt-5 space-y-2">{products.map((product) => <article key={product._id} className="flex items-center justify-between rounded-lg bg-slate-50 p-3 text-sm"><div className="flex items-center gap-3">{product.images?.[0] && <img src={product.images[0]} alt="" className="h-10 w-10 rounded object-cover"/>}<div><p className="font-semibold">{product.name} <span className="font-normal text-slate-500">({product.sku})</span></p><p className="text-slate-500">฿{Number(product.price).toLocaleString()} · {product.brand}</p></div></div><div className="flex gap-2"><button onClick={() => edit(product)} className="text-blue-700">Edit</button><button onClick={() => remove(product._id)} className="text-red-600">Delete</button></div></article>)}</div></section>;
}
